---
  - name: "Add Node.js from source"
    become: true
    shell: |
      curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
      
  - name: "update local repo."
    become: true
    apt:
      update_cache: yes
      
  - name: "upgrade apt packages"
    become: true
    apt:
      upgrade: yes
      
  - name: "remove stale dependencies"
    become: true
    apt:
      autoremove: yes
      
  - name: "Install dependencies [nodejs and npm]."
    become: true
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes
  
  - name: "Install PM2 Globally"
    npm:
      name: pm2
      global: yes


# - name: "Install Node.js 13"
#   shell: |
#     # Install Node.js LTS version as our base Node.js version
#     curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
#     sudo apt-get install -y nodejs

#     # Use n version manager to switch to Node.js v13.8.0
#     sudo npm install -g n
#     sudo n 13.8.0

# - name: "Install PM2 Globally"
#   npm:
#     name: pm2
#     global: yes

# - name: 'update and upgrade packages.' # sudo apt upgrade
#   become: yes
#   apt:
#     upgrade: yes
#     update_cache: yes
#     cache_valid_time: 86400

# - name: "move env variables to /etc/profile.d/"
#   become: true
#   copy:
#     src: myenv.sh
#     dest: /etc/profile.d/