---
  - name: "Update local repo"
    become: true
    apt:
      update_cache: yes
      cache_valid_time: 86400
        
  - name: "remove unneeded deps"
    become: true
    apt:
      autoremove: yes

  - name: "upgrade packages"
    become: true
    apt: 
      upgrade: yes
      
  - name: "Install dependencies [nodejs & npm]"
    become: true
    apt:
      name: ["nodejs","npm"]
      state: latest
      update_cache: yes
  
  - name: "Install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: latest

  - name: Create Backend App Directory
    file:
      path: ~/backend-app
      state: directory
      
  - name: Unarchive files
    become: true
      src: "files/artifact.tar.gz"
      dest: .

  - name: "Start application"
    become: true
    shell: |
      npm install
      pm2 stop default
      pm2 start npm -- start
    
    